# Full app config reference: https://fly.io/docs/reference/configuration/
app = "cdn-2024-08-02"
# Closest to the origin
primary_region = "iad"

kill_signal = "SIGTERM"
kill_timeout = 30

[env]
# We want a low value so that:
# - we leave room for "sidecar" processes (log drains, purge worker, etc.)
# - easier to test what happens when the memory fills up
VARNISH_SIZE="100M"

[[vm]]
size = "shared-cpu-1x"
memory = "256MB"

[deploy]
strategy = "bluegreen"

[[services]]
internal_port = 9000
protocol = "tcp"

[[services.http_checks]]
grace_period = "5s"
interval = "5s"
method = "get"
path = "/varnish_health"
protocol = "http"
timeout = "3s"

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.ports]]
handlers = ["http"]
port = "80"

[services.concurrency]
hard_limit = 2500
soft_limit = 2000
type = "connections"
